fix(sonarr-fr): Update the French guide
TRaSH-Guides/Guides pull request #1459
Opened 2023-07-17 12:56 UTC by NiceTSY

# Pull Request

## Purpose

- Reviewed the presentation for Anime streaming services
- Added the UHD boost/cut
- Added the `Extra` CF to the Unwanted section

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2023-07-17 16:41 UTC, nuxencs requested changes

2023-07-18 08:25 UTC, NiceTSY commented
Interesting, so I believe the original guide is also wrong, because I copy-pasted this part. Want me to have a look and correct those in the Sonarr unwanted section as well?

2023-07-18 14:28 UTC, nuxencs commented
Sure, only looked at your PR so I didn't see that 😄

2023-07-19 09:04 UTC, NiceTSY commented
Haha no worries, should be fixed now :)

2023-07-19 09:09 UTC, nuxencs approved these changes

2023-07-19 09:10 UTC, merged