Add DVD5 and DVD9 to BR-DISK CFs
TRaSH-Guides/Guides pull request #1507
Opened 2023-08-15 19:11 UTC by owine

# Pull Request

## Purpose

Add `DVD5` and `DVD9` to the `BR-DISK` CFs to avoid unwanted full DVD images.

## Approach

Add additional conditions to `BR-DISK` CF, remove requirement on current single condition

## Open Questions and Pre-Merge TODOs

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2023-08-15 20:11 UTC, bakerboy448 approved these changes
lgtm

2023-08-16 16:34 UTC, nuxencs requested changes
I would combine both DVD5 and DVD9 into one condition and use the following value there: `\\b(DVD[59])\\b`.
If we want to keep them you would need to update the regexes to `\\b(DVD5)\\b` and `\\b(DVD9)\\b` respectively.

2023-08-16 16:40 UTC, nuxencs approved these changes
looking better now, @bakerboy448 trolling in here 🤣

2023-08-30 15:20 UTC, owine commented
Based on Discord discussion, opened an issue with Sonarr to get this handled/rejected within Sonarr itself.

https://github.com/Sonarr/Sonarr/issues/5975

2023-08-30 15:20 UTC, closed without merging