feat(starr-fr): French Guide Update
TRaSH-Guides/Guides pull request #1521
Opened 2023-08-22 17:24 UTC by SeiyaGame

# Pull Request

## Purpose

**[New]**
- [Sonarr-FR] Add `FW` to Sonarr` FR Anime Tier 02`
- [Starr-FR] Add `S4LVE` to `FR Scene Groups`
- [Starr-FR] Add `TFA` to `FR Web Tier 01`

**[Updated]**
- [Starr-FR] Upgrade from FR Web Tier 02 to Tier 01 for `FW`

## Requirements

- [X] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [X] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2023-08-22 17:27 UTC, SeiyaGame commented
@NiceTSY take a look, just in case

2023-08-22 19:11 UTC, SeiyaGame commented
@NiceTSY I also made the changes for Dolby V on the CF DV
#1516

2023-08-22 19:34 UTC, NiceTSY commented
Ah thanks for that @SeiyaGame I was planning to do that this weekend :D
Will review this PR tomorrow when I have more time
In the meantime if you could just move `S4LVE` to just after `S0DAP0P` thanks

2023-08-22 19:44 UTC, SeiyaGame commented
> Ah thanks for that @SeiyaGame I was planning to do that this weekend :D Will review this PR tomorrow when I have more time In the meantime if you could just move `S4LVE` to just after `S0DAP0P` thanks

Done :D !

2023-08-23 11:04 UTC, NiceTSY commented on docs/json/radarr/cf/dv-fel.json
This is correct but I think the following should be used instead:
`\\b(dv|dovi|dolby[ .]?v(ision)?)\\b`

2023-08-23 11:04 UTC, NiceTSY commented on docs/json/sonarr/cf/french-anime-tier-02.json
As we have `FW` in FR Web Tier 02, is it necessary to add it in Anime too?
We suggest using the Tiers normally.

2023-08-23 15:34 UTC, SeiyaGame commented on docs/json/radarr/cf/dv-fel.json
The commit 42ea528 change that and also add those I've forgotten ...

2023-08-24 08:47 UTC, NiceTSY commented on docs/json/sonarr/cf/french-anime-tier-02.json
The `IssouCorp` block need to be moved below the `GundamGuy` block to keep the alphabetical order 🙂

2023-08-24 08:47 UTC, NiceTSY commented on docs/json/sonarr/cf/french-anime-tier-03.json
The `kazuizui` block need to be moved below the `HANAMi` block to keep the alphabetical order 🙂

2023-08-24 08:56 UTC, NiceTSY requested changes

2023-08-24 08:56 UTC, NiceTSY commented on docs/json/radarr/cf/french-web-tier-01.json
Sorry, went to fast with this one, `TFA` block need to be moved at the end to keep the alphabetical order

2023-08-24 16:49 UTC, SeiyaGame commented on docs/json/sonarr/cf/french-anime-tier-03.json
Done. (157174c)

2023-08-24 16:49 UTC, SeiyaGame commented on docs/json/sonarr/cf/french-anime-tier-02.json
Done. (157174c)

2023-08-24 16:50 UTC, SeiyaGame commented
Sorry @TRaSH- For all my mistakes, next time I'll do better.

2023-08-24 21:18 UTC, NiceTSY approved these changes
Everything seems alright for me :) 
Thanks for the hardwork @SeiyaGame

2023-08-27 18:21 UTC, SeiyaGame commented
@TRaSH- Ready to merge when you have time

2023-08-27 20:01 UTC, merged