Docs/qbittorrent qbitrr new 3rd party tool
TRaSH-Guides/Guides pull request #1527
Opened 2023-08-28 11:46 UTC by Feramance

# Pull Request

## Purpose

Update qBitrr doc to reflect recent updates

## Requirements

- [x ] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [ x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2023-08-28 16:21 UTC, bakerboy448 submitted a review, later dismissed

2023-08-28 16:21 UTC, bakerboy448 commented on docs/Downloaders/qBittorrent/3rd-party-tools.md
> +- Search requests from [Overseerr](https://github.com/sct/overseerr) or [Ombi](https://github.com/Ombi-app/Ombi).
Add no referrer

2023-08-30 10:45 UTC, TRaSH- commented
> All done

Not really, you removed the link to ombi and overseerr.
just add after the link: `{:target="_blank" rel="noopener noreferrer"}`
this was when they click on the link it will open on a new page/tab etc

2023-08-30 12:33 UTC, Feramance commented
Updated as explained

2023-08-31 01:41 UTC, bakerboy448 commented on docs/Downloaders/qBittorrent/3rd-party-tools.md
> +- Usage of [ffprobe](https://github.com/FFmpeg/FFmpeg) to ensure downloaded entries are valid media.
```suggestion
- Usage of [ffprobe](https://github.com/FFmpeg/FFmpeg){:target="_blank" rel="noopener noreferrer"} to ensure downloaded entries are valid media.
```
?

2023-08-31 08:55 UTC, Feramance commented on docs/Downloaders/qBittorrent/3rd-party-tools.md
> +- Usage of [ffprobe](https://github.com/FFmpeg/FFmpeg) to ensure downloaded entries are valid media.
Fixed

2023-08-31 08:55 UTC, Feramance commented
Should be all good now

2023-09-08 13:31 UTC, bakerboy448 requested changes
Sorry for the delay on this

2023-09-08 13:32 UTC, bakerboy448 approved these changes

2023-09-08 13:32 UTC, merged