feat(starr): add custom formats for Japanese streaming services `FOD`, `TVer` and `U-NEXT`
TRaSH-Guides/Guides pull request #1594
Opened 2023-10-16 11:30 UTC by Kuredant

# Pull Request

## Purpose

- Add the following streaming service to the guides
  - `FOD`
  - `TVer`
  - `U-NEXT`

## Approach

Added: Streaming Service `FOD`, `TVer` and `U-NEXT` with a score of `0`, mainly for the naming scheme

- [x]  Add `FOD`, `TVer` and `U-NEXT` Streaming Service CF to Radarr
- [x]  Added Radarr hashcode for `FOD`, `TVer` and `U-NEXT` Streaming Service CF
- [x]  Provided a link to your regex example of your Radarr Custom Formats
- [x]  Add `FOD`, `TVer` and `U-NEXT` Streaming Service CF to Radarr Collection Table
- [x]  Add `FOD`, `TVer` and `U-NEXT` Streaming Service CF to Radarr Guide Quality Profiles
- [x]  Add new `FOD`, `TVer` and `U-NEXT` Streaming Service CF to Sonarr v4
- [x]  Added Sonarr hashcode for `FOD`, `TVer` and `U-NEXT` Streaming Service CF
- [x]  Provided a link to your regex example of your Sonarr  Custom Formats
- [x]  Add `FOD`, `TVer` and `U-NEXT` Streaming Service CF to Sonarr Collection Table
- [x]  Add `FOD`, `TVer` and `U-NEXT` Streaming Service CF to Sonarr Guide Quality Profiles
- [x]  Test changes in local test setup
- [ ]  **Added Changelog after review and approve**

## Open Questions and Pre-Merge TODOs

- Should the Sonarr v3 release profiles also be updated? In that case, what score would be appropriate?

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2023-10-16 17:16 UTC, bakerboy448 commented
What series and movies do these groups typically cover?

2023-10-17 17:18 UTC, Kuredant commented
> What series and movies do these groups typically cover?

They're Japanese streaming services, so mostly Japanese TV shows, anime, and Asian dramas.
[FOD](https://fod-sp.fujitv.co.jp) is mostly for Fuji TV contents, [TVer](https://tver.jp) and [U-NEXT](https://video.unext.jp) both get releases from various TV channels along with exclusives.

> The new Sonarr custom formats will need to have the default score applied to them, which is 50. E.g.:
> 
> ```yaml
> {
>   "trash_id": "7be9c0572d8cd4f81785dacf7e85985e",
>   "trash_regex": "https://regex101.com/r/CbFoaJ/1",
>   "name": "FOD",
> ```
> 
> needs to be:
> 
> ```yaml
> {
>  "trash_id": "7be9c0572d8cd4f81785dacf7e85985e",
>  "trash_score": 50,
>  "trash_scores": {
>    "default": 50
>  },
>  "trash_regex": "https://regex101.com/r/CbFoaJ/1",
>  "name": "FOD",
> ```
> 
> The V3 guide section can also use those same scores.

Thanks, I added the missing scores to Sonarr CFs and regexes for Sonarr V3.
Please let me know if anything else is missing.

2023-10-17 21:24 UTC, yammes08 requested changes
Made one suggestion as it looks like you've got a wrong regex match in there. Other than that, looks good to me.

2023-10-17 21:24 UTC, yammes08 commented on docs/json/sonarr/cf/tver.json
> +        "value": "\\b(u-next)\\b"
```suggestion
        "value": "\\b(tver)\\b"
```

2023-10-17 21:33 UTC, yammes08 commented
nuxen - I just thought I'd better get a second pair of eyes on this 😄

2023-10-18 01:06 UTC, Kuredant commented on docs/json/sonarr/cf/tver.json
> +        "value": "\\b(u-next)\\b"
Sorry for that, it should be fixed now.

2023-11-13 21:07 UTC, TRaSH- commented
@nuxencs could you review this one please ?

2023-11-13 21:07 UTC, nuxencs commented
give me a few minutes

2023-11-13 21:38 UTC, nuxencs requested changes

2023-11-13 21:38 UTC, nuxencs commented on docs/json/sonarr/cf/fod.json
> +  "trash_score": 50,
remove deprecated `trash_score`
```suggestion
```

2023-11-13 21:38 UTC, nuxencs commented on docs/json/sonarr/cf/tver.json
> +  "trash_score": 50,
remove deprecated `trash_score`
```suggestion
```

2023-11-13 21:38 UTC, nuxencs commented on docs/json/sonarr/cf/u-next.json
> +  "trash_score": 50,
remove deprecated `trash_score`
```suggestion
```

2023-11-13 21:39 UTC, nuxencs commented
> nuxen - I just thought I'd better get a second pair of eyes on this 😄

sorry completely missed this, if you tag me I'm more likely to see it 😄

2023-11-13 21:42 UTC, yammes08 commented
> > nuxen - I just thought I'd better get a second pair of eyes on this 😄
> 
> sorry completely missed this, if you tag me I'm more likely to see it 😄

My bad, sorry 😆

2023-11-13 21:44 UTC, nuxencs approved these changes

2023-11-13 21:46 UTC, yammes08 approved these changes

2023-11-13 21:48 UTC, merged