style(2-why.md): Rephrase SQP2's "Why?" to make it clearer.
TRaSH-Guides/Guides pull request #1816
Opened 2024-03-01 12:12 UTC by AN1MATEK

Rephrased the sentences to make it more clear.

# Pull Request

## Purpose

Just a rephrase of the statements here. The "must support DoVi from start to finish" was a little harsh for people with Samsung TVs, specially because down under in the guide there is a way to configure to avoid DV (WEB-DL) and boost HDR10+.

## Approach

Just trying to make the text more clear.

## Open Questions and Pre-Merge TODOs

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2024-03-01 21:35 UTC, nuxencs approved these changes
lgtm

2024-03-01 21:38 UTC, zakkarry requested changes
just a few suggestions

2024-03-01 21:38 UTC, zakkarry commented on includes/sqp/2-why.md
> +    - You don't want to wait for the HQ Encodes to be released to be able to watch them.
```suggestion
    - You have a decent audio setup that supports all HD audio formats (Atmos, TrueHD, etc).
    - You have a TV that supports enhanced HDR formats, (DV and/or HDR10+).
    - You want the highest possible quality to watch but want to also save space for archiving without giving up video and audio quality.
    - You don't want to wait longer for the HQ Encodes to be released.

2024-03-02 09:39 UTC, zakkarry approved these changes

2024-03-02 11:34 UTC, nuxencs approved these changes

2024-03-03 14:26 UTC, merged