fix(starr): AMZN CF should also match AmazonHD
TRaSH-Guides/Guides pull request #1829
Opened 2024-03-05 18:49 UTC by lucasreiners

# Pull Request

## Purpose

A lot of the german releases coming from amazon video contain the keyword "AmazonHD" in the release title, which is currently not matched by the CF AMZN, which only searches for "amazon" or "amzn".

Regex test: https://regex101.com/r/aNiJfh/1

## Approach

This PR adds "AmazonHD" for the AMZN CF for both, sonarr and radarr

## Open Questions and Pre-Merge TODOs

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2024-03-05 19:40 UTC, TRaSH- commented
https://regex101.com/r/aNiJfh/2

2024-03-05 20:01 UTC, lucasreiners commented
> https://regex101.com/r/aNiJfh/2

Tried it, but that doesn't give the expected result. I added more exmaples:

https://regex101.com/r/aNiJfh/3

2024-03-06 18:04 UTC, nuxencs requested changes
https://regex101.com/r/aNiJfh/4

2024-03-06 18:04 UTC, nuxencs commented on docs/json/radarr/cf/amzn.json
> +        "value": "\\b(amzn|amazon|amazonhd)\\b"
```suggestion
        "value": "\\b(amzn|amazon|amazon(hd)?)\\b"
```

2024-03-06 18:04 UTC, nuxencs commented on docs/json/sonarr/cf/amzn.json
> +        "value": "\\b(amzn|amazon|amazonhd)\\b"
```suggestion
        "value": "\\b(amzn|amazon|amazon(hd)?)\\b"
```

2024-03-06 19:27 UTC, lucasreiners commented
> https://regex101.com/r/aNiJfh/4

Perfect, very neat solution, thank you!

2024-03-06 19:34 UTC, nuxencs approved these changes
lgtm

2024-03-07 16:24 UTC, merged