fix(starr): netflix CF should also match NetflixHD in the release title
TRaSH-Guides/Guides pull request #1845
Opened 2024-03-16 13:47 UTC by lucasreiners

# Pull Request

## Purpose

German releases often use NetflixHD in the release title, which is currently not matched by the custom format.
Basically the same as in https://github.com/TRaSH-Guides/Guides/pull/1829

## Approach

Added optional HD suffix to the custom format

## Open Questions and Pre-Merge TODOs

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2024-03-17 09:10 UTC, TRaSH- commented
Don't they also use netflixuhd ?

2024-03-17 10:05 UTC, lucasreiners commented
Actually never saw that, so I am not sure, but if you would like, I could optionally add that, too

2024-03-17 17:16 UTC, TRaSH- commented
> Actually never saw that, so I am not sure, but if you would like, I could optionally add that, too

yeah just add it, i think i found part of it in the Sonarr source code

2024-03-17 18:38 UTC, lucasreiners commented
Updated regex test:
https://regex101.com/r/QpfWrs/2

2024-03-18 17:30 UTC, TRaSH- commented
@nuxencs could you review this one ?

2024-03-18 19:24 UTC, nuxencs requested changes
just a small simplification

2024-03-18 19:24 UTC, nuxencs commented on docs/json/radarr/cf/nf.json
> +        "value": "\\b(nf|netflix(u)?(hd)?)\\b"
https://regex101.com/r/pWZokU/1
```suggestion
        "value": "\\b(nf|netflix(u?hd)?)\\b"
```

2024-03-18 19:24 UTC, nuxencs commented on docs/json/sonarr/cf/nf.json
> +        "value": "\\b(nf|netflix(u)?(hd)?)\\b"
https://regex101.com/r/pWZokU/1
```suggestion
        "value": "\\b(nf|netflix(u?hd)?)\\b"
```

2024-03-21 12:33 UTC, lucasreiners commented
Thank you, simplicfication still works as expected:
https://regex101.com/r/QpfWrs/3

2024-03-21 15:29 UTC, nuxencs approved these changes

2024-03-21 15:29 UTC, merged