Update index.md
TRaSH-Guides/Guides pull request #1852
Opened 2024-03-21 22:28 UTC by OneRadRedDad

# Pull Request

## Purpose

To update grammar and improve readability of index.md

## Requirements

- [X] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [X] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2024-03-23 12:55 UTC, TRaSH- commented
Thnx, i will let our new own grammar control review this one.
not my place to argue about English grammar

2024-03-23 17:37 UTC, zakkarry requested changes
Just my recommendations on language as @TRaSH- requested.

Feel free to discuss/comment on wording or grammar if you feel so inclined :)

2024-03-23 17:37 UTC, zakkarry commented on docs/index.md
> +I decided to fine tune my quality profile settings to try to get the releases & quality I preferred. On Discord, I noticed that others ran in to the same issue, so I explained how I managed to get it
```suggestion
I decided to fine-tune my quality profile settings to try and get the releases and qualities I preferred. While on Discord, I noticed that others ran into the same issue, so I explained how I managed to solve this. Once I started having to explain more often, I decided to write it down and make it public so I could easily link to it when needed.

2024-03-23 17:37 UTC, zakkarry commented on docs/index.md
> +I try to make my guides as easy as possible for everyone to understand. In my opinion, pictures often explain more than just some text.
```suggestion
I try to make my guides as easy as possible to understand. In my opinion, pictures often explain more than just some text.

2024-03-23 17:37 UTC, zakkarry commented on docs/index.md
> +If you have questions, suggestions, requests, or want to contribute, click the chat badge to join the Discord Channel. There, you can ask your questions directly. Alternatively, you can use the follo
```suggestion
If you have questions, suggestions, or requests, or want to contribute, click the chat badge to join the Discord Channel. There you can ask your questions directly, or you can use the following [link](https://github.com/TRaSH-Guides/Guides/issues){:target="_blank" rel="noopener noreferrer"} to open an issue on GitHub.

2024-03-23 17:37 UTC, zakkarry commented on docs/index.md
> +I have tested most things myself and I have tried to see if I could tune them a bit more to my needs (and sometimes even for others).
```suggestion
The information provided in the guides has been gathered from different sources such as support forums, Reddit, Discord, developed based on user input, or from the development teams themselves.
I have tested and tuned most things with the ultimate goal being to have them in line with my, and sometimes others', needs.

2024-03-23 17:37 UTC, zakkarry commented on docs/index.md
> +You use everything here at your own risk. I am not responsible if something happens to your setup or collection!
```suggestion
All of the information provided in these guides, as well as in Discord or any guides-related mediums, is to be used at your own risk. I am not responsible if something happens to your setup or collection!

2024-03-23 17:52 UTC, TRaSH- commented
@OneRadRedDad do you agree with the suggested changes ?
i will add the suggestions in a batch and merge them together with the PR

2024-03-24 23:14 UTC, OneRadRedDad commented
> @OneRadRedDad do you agree with the suggested changes ? i will add the suggestions in a batch and merge them together with the PR

I committed the ones I take no issue with. I'd like to propose some further changes to the remaining suggestions, but won't be able to do so for another 12-24 hours.

2024-03-26 13:26 UTC, OneRadRedDad commented
@zakkarry I've made some slight tweaks to your remaining two suggestions. Let me know what you think.

2024-03-26 13:52 UTC, zakkarry approved these changes

2024-03-26 13:52 UTC, zakkarry commented
lgtm

2024-03-26 13:53 UTC, zakkarry commented
@TRaSH- merge whenever

2024-03-30 13:39 UTC, merged