feat(guide): Starr language tips add German dual and multi
TRaSH-Guides/Guides pull request #1880
Opened 2024-04-13 09:12 UTC by TRaSH-

# Pull Request

## Purpose

Dual and Multi language is also picked up as original audio, for some users it's a preferred option, others rather don't get those releases because there is no way to determine upfront which audio track is used as main audio track.

## Approach

## Open Questions and Pre-Merge TODOs

- [x] Added a Custom Format  provided by @mynameisbogdan that matches on German + Dual/Multi audio.
- [x] Added a option If you DON'T WANT that your media file has a German audio track included.
- [x] Added a option If you PREFER that your media file has a German audio track included.

## Requirements

- [ ] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [ ] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2024-04-16 14:27 UTC, nuxencs approved these changes
lgtm

2024-04-16 14:28 UTC, nuxencs commented
probably a good idea to let @zakkarry proofread it 😄

2024-04-16 14:37 UTC, zakkarry requested changes
nits

2024-04-16 14:37 UTC, zakkarry commented on docs/json/guide-only/language-german-and-original.json
> +  "trash_description": "Language: German Dual Language and Multi-language releases",
```suggestion
  "trash_description": "Language: German Dual and Multi language releases",
```
I think wording this like this is better

2024-04-16 14:37 UTC, zakkarry commented on docs/Radarr/Tips/How-to-setup-language-custom-formats.md
> +- If you **PREFER** that your media file has a German audio track included then you can add this Custom Format with a positive score.
```suggestion
- If you **DON'T WANT** your media file to have a German audio track included, add this Custom Format with a score of `-10000`.
- If you **PREFER** your media file to have a German audio track included, add this Custom Format with a positive score.

2024-04-16 14:37 UTC, zakkarry commented on docs/Radarr/Tips/How-to-setup-language-custom-formats.md
> +This Custom Format can be used in several ways,
```suggestion
This Custom Format can be used in several ways:

2024-04-16 14:37 UTC, zakkarry commented on docs/Radarr/Tips/How-to-setup-language-custom-formats.md
> +!!! info "In general Dual/Multi stands for original language (*movies/show original language*) + foreign language(s), which audio track is used as first track isn't always known."
```suggestion
Here we will add special cases that often are related to specific languages.
example: German Dual Language and/or Multi-language releases

!!! info "In general, Dual/Multi stands for original language (*movies/show original language*) + foreign language(s). Which audio track being used as the first track isn't always known based on the naming."

2024-05-06 22:29 UTC, zakkarry requested changes
only had one suggestion for a block, didn't check anything besides grammar.

2024-05-06 22:29 UTC, zakkarry commented on docs/Radarr/Tips/How-to-setup-language-custom-formats.md
> +This Custom Format can be used in several ways:
```suggestion
## Language Special Cases

Here we will add special cases that often are related to specific languages.
example: German Dual Language and/or Multi-language releases

!!! info "In general, Dual/Multi in a release title stands for original language (*movies/show original language*) + foreign language(s). Which audio track is used for the first track isn't always known based solely on the naming."

### Language: German + Original

This Custom Format can be used in two ways:
```

2024-05-09 13:42 UTC, zakkarry approved these changes

2024-05-12 10:54 UTC, nuxencs requested changes
newline for admonition per mkdocs documentation

2024-05-12 10:54 UTC, nuxencs commented on docs/Radarr/Tips/How-to-setup-language-custom-formats.md
> +!!! tip
```suggestion
!!! tip

```

2024-05-12 10:54 UTC, nuxencs commented on docs/Radarr/Tips/How-to-setup-language-custom-formats.md
> +!!! tip
```suggestion
!!! tip

```

2024-05-12 10:54 UTC, nuxencs commented on docs/Radarr/Tips/How-to-setup-language-custom-formats.md
> +!!! tip
```suggestion
!!! tip

```

2024-05-12 10:54 UTC, nuxencs commented on docs/Radarr/Tips/How-to-setup-language-custom-formats.md
> +!!! tip
```suggestion
!!! tip

```

2024-05-15 18:25 UTC, nuxencs approved these changes
lgtm

2024-05-15 18:28 UTC, merged