feat(guides): Improve description for `x265 (no HDR/DV)`, `x265 (HD)` and `SDR (no WEBDL)`
TRaSH-Guides/Guides pull request #1941
Opened 2024-05-19 16:51 UTC by TRaSH-

# Pull Request

## Purpose

Improve description for `x265 (no HDR/DV)`, `x265 (HD)` and `SDR (no WEBDL)`

## Approach

Tried to improved description for `x265 (no HDR/DV)`, `x265 (HD)` and `SDR (no WEBDL)`, and asked in Discord if the users that had issues understanding the former description if they preferred the new description and with it understand the description.

## Open Questions and Pre-Merge TODOs

- [x] Tested the changes locally for errors

## Requirements

- [ ] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [ ] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2024-05-19 21:40 UTC, yammes08 submitted a review, later dismissed

2024-05-19 21:40 UTC, yammes08 commented
I've approved it, but @zakkarry might want to take a language/grammar pass?

2024-05-19 23:06 UTC, zakkarry requested changes
This looks mostly good, just a few small changes.

Might want to check how the particular bullet points render in the last 2 before merging.

2024-05-19 23:06 UTC, zakkarry commented on includes/cf-descriptions/x265-no-hdrdv-radarr.md
> +*Being that some NF releases won't be released as 4k, but you want to have DV/HDR releases.*
```suggestion
*Since some NF releases won't be released as 4k, this allows you to still have the DV/HDR releases.*

2024-05-19 23:06 UTC, zakkarry commented on includes/cf-descriptions/x265-no-hdrdv-sonarr.md
> +*Being that some NF releases won't be released as 4k, but you want to have DV/HDR releases.*
```suggestion
*Since some NF releases won't be released as 4k, this allows you to still have the DV/HDR releases.*

2024-05-19 23:06 UTC, zakkarry commented on includes/cf/radarr-optional-uhd.md
> +        - `SDR (no WEBDL)` over the `SDR`, Read the Why below and don't forget to read the warning :warning:
```suggestion
        - **For details on "Why" and a potential warning :warning: please see the notes below.**
        - `x265 (no HDR/DV)` over the `x265 (HD)`
        - `SDR (no WEBDL)` over the `SDR`

2024-05-19 23:06 UTC, zakkarry commented on includes/cf/sonarr-optional-uhd.md
> +        - `SDR (no WEBDL)` over the `SDR`, Read the Why below and don't forget to read the warning :warning:
```suggestion
        - **For details on "Why" and a potential warning :warning: please see the notes below.**
        - `x265 (no HDR/DV)` over the `x265 (HD)`
        - `SDR (no WEBDL)` over the `SDR`

2024-05-20 08:44 UTC, TRaSH- commented
> This looks mostly good, just a few small changes.
> 
> Might want to check how the particular bullet points render in the last 2 before merging.

![image](https://github.com/TRaSH-Guides/Guides/assets/6155095/de1ec48e-e47f-489e-aab2-6cd7133c2bc0)

Looks good thnx

2024-05-22 19:15 UTC, zakkarry approved these changes

2024-05-22 19:16 UTC, merged