chore(guide): Changed discord shield to button
TRaSH-Guides/Guides pull request #1973
Opened 2024-06-10 18:37 UTC by TRaSH-

# Pull Request

## Purpose

- Changed discords shields.io to a click here button, hopefully to solve the rate limiting issue.
- Changed `{! include-markdown "../../../includes/support.md" !}` to `--8<-- "includes/support.md"` to be more consistent with the other pages and less failures depending on where the page is located 

## Approach

- [x] Changed discords shields.io to a click here button
- [x] Changed `{! include-markdown "../../../includes/support.md" !}` to `--8<-- "includes/support.md"`

## Open Questions and Pre-Merge TODOs

## Requirements

- [ ] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [ ] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2024-06-10 22:45 UTC, zakkarry commented
Not that it matters to me, but if you're using cloudflare for this, couldn't you just cache the asset and set a TTL on the image so it updates only every 5m or something rather than just removing it?

I'm not sure what rate limiting issue really is, or what its cause, but it seems like something easily fixed without entirely removing it?

@bakerboy448

2024-06-10 23:58 UTC, bakerboy448 commented
Zak's triage seems likely accurate

2024-06-11 04:39 UTC, TRaSH- commented
I only removed it from the guide pages and kept it on the main page (index) where it also shows the other badges.

I wouldn't know if I can cache the shields, used to work always without issues. The others do, except the discord one.

2024-06-11 19:31 UTC, zakkarry requested changes
cached image on cloudflare

2024-06-11 19:31 UTC, zakkarry commented on docs/Plex/Tips/Plex-media-server.md
> +    We will only cover settings that we think might be interesting or are personal preference, if you would like me to cover some other settings, please contact us on discord.
```suggestion
    We will only cover settings that we think might be interesting or are personal preference, if you would like me to cover some other settings, please contact me on [![Discord chat](https://trash-guides.info/assets/discord.png)](https://trash-guides.info/discord){:target="\_blank" rel="noopener noreferrer"}

2024-06-11 19:31 UTC, zakkarry commented on docs/Radarr/radarr-setup-quality-profiles.md
> +    <center>[ Click For Support ](https://trash-guides.info/discord){ .md-button .md-button--primary }</center>
```suggestion
    [![Discord chat](https://trash-guides.info/assets/discord.png){ .off-glb }](https://trash-guides.info/discord){:target="_blank" rel="noopener noreferrer"}

2024-06-11 19:31 UTC, zakkarry commented on docs/Sonarr/sonarr-setup-quality-profiles.md
> +    <center>[ Click For Support ](https://trash-guides.info/discord){ .md-button .md-button--primary }</center>
```suggestion
    [![Discord chat](https://trash-guides.info/assets/discord.png){ .off-glb }](https://trash-guides.info/discord){:target="_blank" rel="noopener noreferrer"}

2024-06-11 19:31 UTC, zakkarry commented on includes/cf/score-attention.md
> +    <center>[ Click For Support ](https://trash-guides.info/discord){ .md-button .md-button--primary }</center>
```suggestion
    [![Discord chat](https://trash-guides.info/assets/discord.png){ .off-glb }](https://trash-guides.info/discord){:target="_blank" rel="noopener noreferrer"}

2024-06-11 19:31 UTC, zakkarry commented on includes/support.md
> +<!-- markdownlint-enable MD041-->
```suggestion

    [![Discord chat](https://trash-guides.info/assets/discord.png){ .off-glb }](https://trash-guides.info/discord){:target="_blank" rel="noopener noreferrer"}
<!-- markdownlint-enable MD041-->

2024-06-11 19:31 UTC, zakkarry commented on docs/index.md
> +<center>[ Click For Support ](https://trash-guides.info/discord){ .md-button .md-button--primary }</center>
```suggestion
- If you have questions or suggestions, click the button below to join our Discord server.
- If you want to contribute, feel free to create a PR (Pull Request).
- If you found a actual issue related to the guide you can open a Github [issue](https://github.com/TRaSH-Guides/Guides/issues){:target="\_blank" rel="noopener noreferrer"}.

[![Discord chat](https://trash-guides.info/assets/discord.png){ .off-glb }](https://trash-guides.info/discord){:target="_blank" rel="noopener noreferrer"}

2024-06-12 04:15 UTC, merged