chore(guides): Update changelog to 2024-06-13
TRaSH-Guides/Guides pull request #1975
Opened 2024-06-13 17:12 UTC by bakerboy448

changelog

2024-06-13 17:13 UTC, bakerboy448 commented on docs/updates.txt
> +- Synology: [fix(jellyfin): add quicksync video check (#211)]((https://github.com/TRaSH-Guides/Synology-Templates/pull/211)
```suggestion
- Synology: [fix(jellyfin): add quicksync video check (#211)](https://github.com/TRaSH-Guides/Synology-Templates/pull/211)
```

2024-06-13 19:47 UTC, nuxencs reviewed
lgtm but might wait on #1974

2024-06-14 02:47 UTC, zakkarry requested changes

2024-06-14 02:47 UTC, zakkarry commented on docs/updates.txt
> +- [chore(guide): Changed discord shield to button (#1973)](https://github.com/TRaSH-Guides/Guides/pull/1973)
```suggestion
- [chore(guide): Changed discord shield to button (#1973)](https://github.com/TRaSH-Guides/Guides/pull/1973)
- [feat(guide): Update Setup TorGuard for port forwarding Guide (#1974)](https://github.com/TRaSH-Guides/Guides/pull/1974)

2024-06-14 03:14 UTC, zakkarry approved these changes

2024-06-14 03:15 UTC, merged