Fix/sonarr radarr cf image
TRaSH-Guides/Guides pull request #1991
Opened 2024-06-28 13:25 UTC by washedszn

# Pull Request

## Purpose

Addresses issue #1989 - also discovered that AV1 was missing from the anime radarr CF's, so I've added that too.

## Approach

Replaced the two CF images for sonarr and radarr with images which align with the scores in the CF table. As for adding AV1, I added `anime-radarr` to the AV1 JSON object with a score of `-10000` and added a new line to the CF table `radarr-anime.md` so that AV1 is shown and linked correctly

## Open Questions and Pre-Merge TODOs

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2024-06-28 14:18 UTC, nuxencs requested changes
Changes look good, but could you maybe update docs/Radarr/images/cfa-complete.png and docs/Sonarr/images/cfa-complete.png as well? 😄

2024-06-28 15:02 UTC, washedszn commented
> Changes look good, but could you maybe update `docs/Radarr/images/cfa-complete.png` and `docs/Sonarr/images/cfa-complete.png` as well? 😄

Just added them! However it got me thinking, for radarr and sonarr, there are two CF images for when `Dual Audio` or `Uncensored` have different scores. Reckon it's worth grabbing new images for them as well? or maybe removing them as it's a bit repetitive

2024-06-29 04:46 UTC, zakkarry commented
It's probably best to keep the image as consistent as we can with the scores, especially at PR time.

It's somewhat iffy on whether they can always be remembered to be up to date with the guide (as a whole) - but if we're updating things and its not spur of the moment, I think it's probably best to try and be as consistent at the PR time as possible....regardless of repetition.

In my opinion, the should align with what the majority of users would be seeing in their instance. If there are multiple options than the "most used" option would probably align best with what should be seen in screenshots.

2024-06-29 05:33 UTC, FonduemangVI approved these changes

2024-06-29 05:33 UTC, merged