feat(starr): Update of the French Guide
TRaSH-Guides/Guides pull request #2087
Opened 2024-10-08 21:12 UTC by NiceTSY

# Pull Request

## Purpose

Updating the French Guide to include improvement from latest Radarr/Sonarr changes, to improve upon specific settings, and streamline some approach.

## Open Questions and Pre-Merge TODOs

- [x] Implement new Language CFs to align with the rest of the guide language recommendation
- [x] Update the Radarr French Guide
- [ ] Update the Sonarr French Guide
- [ ] (Maybe) Update the Sonarr French Anime Guide
- [ ] Check language errors again
- [ ] Check technical errors again
- [ ] Check scoring a last time

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2024-11-01 19:10 UTC, TRaSH- requested changes

2024-11-02 09:52 UTC, NiceTSY commented on includes/french-guide/radarr-cf-french-hd-bluray-web-scoring-en.md
Thanks, I tried to put everything under `french-xxx` but missed some apparently will check and update those.

2024-11-09 20:55 UTC, TRaSH- submitted a review, later dismissed

2024-11-09 21:56 UTC, TRaSH- commented
Added do not merge because there are still a view things that might need to be updated

2024-11-16 14:37 UTC, TRaSH- commented
Do you still want to update the anime guide, or is that something for another time?

2024-11-16 14:43 UTC, TRaSH- commented
I've got a green light to merge this in our dev channel. The anime guide will be updated later.

2024-11-16 14:43 UTC, merged

2024-11-20 07:46 UTC, LhuanDula commented
Hi,
I noticed that the multi and multi-french trashids format have been deleted but they are still mentioned in the guide (both in english and french).
Are we supposed to drop the use of the multi-french custom format (which is a shame because that's the one that has really worked for me)?
Cheers,