Remove groups from anime remux tier
TRaSH-Guides/Guides pull request #2177
Opened 2024-12-24 21:47 UTC by rg9400

# Pull Request

## Purpose

## Approach

## Open Questions and Pre-Merge TODOs

## Requirements

- [ ] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [ ] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2024-12-24 22:16 UTC, TRaSH- commented on docs/json/sonarr/cf/anime-bd-tier-04-seadex-muxers.json
> +  ]
```suggestion
 
```

2024-12-24 22:18 UTC, TRaSH- commented on docs/json/sonarr/cf/anime-bd-tier-04-seadex-muxers.json
> +  ]
```suggestion
```

2024-12-24 22:19 UTC, TRaSH- requested changes
These two lines needs to be removed

2024-12-24 23:54 UTC, TRaSH- approved these changes

2024-12-26 04:38 UTC, FonduemangVI approved these changes
Good to go

2024-12-26 04:39 UTC, merged